/**
 * exportManager.js -- Orchestrates mould file export (STL/STEP ZIP download).
 *
 * Flow:
 *   1. User clicks Download -> downloadMouldZip() called
 *   2. Calls geometryBridge.exportParts() -> worker generates STL/STEP ArrayBuffers + volumes
 *   3. Creates JSZip, adds files + comprehensive readme with plaster calculations
 *   4. Generates ZIP blob and triggers browser download
 *
 * JSZip is loaded via CDN script tag (window.JSZip). NOT imported as ES module.
 */

import * as geometryBridge from './geometryBridge.js';
import { calculatePlaster } from './plasterCalculator.js';

/**
 * Trigger a browser file download from a Blob.
 *
 * @param {Blob} blob - File content.
 * @param {string} filename - Download filename.
 */
function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Generate a comprehensive readme for the ZIP download.
 *
 * Includes: file list, mould settings, assembly instructions,
 * and plaster mixing calculations.
 *
 * @param {Object} params
 * @param {string[]} params.partNames - List of part file names included.
 * @param {Object} params.mouldParams - Mould generation parameters.
 * @param {Object} params.volumes - Volume measurements from worker.
 * @param {'standard'|'high'} params.resolution - STL resolution used.
 * @param {boolean} [params.includeStep] - Whether STEP files are included.
 * @returns {string} Readme text content.
 */
function generateReadme({ partNames, mouldParams, volumes, resolution, includeStep = false }) {
  const date = new Date().toISOString().split('T')[0];
  const cavityCc = (volumes.cavityVolumeMm3 || 0) / 1000;
  const potCc = (volumes.proofVolumeMm3 || 0) / 1000;
  const plaster = calculatePlaster(cavityCc);

  const splitLabel = mouldParams.splitCount === 4 ? 'Quarters (4 pieces)' : 'Halves (2 pieces)';
  const slipWellLabel = mouldParams.slipWellType === 'none' ? 'None'
    : mouldParams.slipWellType === 'tall' ? 'Tall (50mm)' : 'Regular (25mm)';

  let text = '';
  text += 'POTTERY MOULD PARTS\n';
  text += '====================\n';
  text += '\n';
  text += `Generated by Pottery Mould Generator\n`;
  text += `Date: ${date}\n`;
  text += '\n';
  text += '\n';
  text += 'MOULD SETTINGS\n';
  text += '--------------\n';
  text += `  Shrinkage:          ${(mouldParams.shrinkageRate * 100).toFixed(1)}%\n`;
  text += `  Wall thickness:     ${mouldParams.wallThickness} mm\n`;
  text += `  Slip well:          ${slipWellLabel}\n`;
  text += `  Plaster cavity gap: ${mouldParams.cavityGap} mm\n`;
  text += `  Mould split:        ${splitLabel}\n`;
  text += `  Assembly clearance:  ${mouldParams.clearance} mm\n`;
  text += `  Outer wall:         ${mouldParams.outerWallThickness} mm\n`;
  text += `  STL resolution:     ${resolution}\n`;
  text += '\n';
  text += '\n';
  text += 'FILES INCLUDED\n';
  text += '--------------\n';
  for (const name of partNames) {
    text += `  ${name}.stl\n`;
    if (includeStep) {
      text += `  ${name}.step\n`;
    }
  }
  text += '  README.txt (this file)\n';
  text += '\n';
  text += '\n';
  text += 'PLASTER CALCULATIONS\n';
  text += '--------------------\n';
  text += `  Pot volume (fired):      ${Math.round(potCc)} cm3 (${Math.round(potCc)} mL)\n`;
  text += `  Plaster cavity volume:   ${Math.round(cavityCc)} cm3\n`;
  text += '\n';
  text += '  Using USG No.1 Pottery Plaster (water:plaster = 70:100)\n';
  text += '\n';
  text += `  >>> Plaster needed:  ${plaster.plasterGrams} g <<<\n`;
  text += `  >>> Water needed:    ${plaster.waterMl} mL <<<\n`;
  text += '\n';
  text += `  Total slurry weight: ${plaster.totalSlurryGrams} g\n`;
  text += '\n';
  text += '  TIP: Mix 10% extra to account for spillage and mixing losses.\n';
  text += `        -> Plaster: ${Math.round(plaster.plasterGrams * 1.1)} g\n`;
  text += `        -> Water:   ${Math.round(plaster.waterMl * 1.1)} mL\n`;
  text += '\n';
  text += '\n';
  text += 'ASSEMBLY INSTRUCTIONS\n';
  text += '---------------------\n';
  text += '  1. Print all STL files in PLA or PETG (0.2mm layer height recommended)\n';
  text += '  2. Lightly sand mating surfaces if needed for a snug fit\n';
  text += '  3. Place the inner mould on the ring, aligning the ridge/groove features\n';
  text += '  4. Assemble outer mould halves around the inner mould on the ring\n';
  text += '  5. Secure outer mould pieces with rubber bands or clamps\n';
  text += '  6. Seal seams with soft clay or petroleum jelly to prevent leaks\n';
  text += '  7. Mix plaster and water (quantities above) -- add plaster to water, stir gently\n';
  text += '  8. Pour plaster through the pour hole in the ring\n';
  text += '  9. Let set for 30-45 minutes before removing mould parts\n';
  text += ' 10. Allow plaster mould to dry for 24-48 hours before first use\n';
  text += '\n';
  text += '\n';
  text += 'NOTES\n';
  text += '-----\n';
  text += '  - Plaster calculations assume USG No.1 Pottery Plaster at 70:100 consistency.\n';
  text += '    Adjust ratios if using a different plaster brand.\n';
  text += '  - The cavity volume is an approximation. Actual plaster needed may vary\n';
  text += '    slightly due to assembly features and seal quality.\n';
  text += '  - For best results, sieve plaster before mixing to remove lumps.\n';
  text += '  - Water temperature: use room temperature water (18-22C / 65-72F).\n';
  text += '\n';
  text += '---\n';
  text += 'Generated by moulds.thepotteryacademy.com\n';

  return text;
}

/**
 * Download all mould parts as a ZIP file containing binary STL files.
 *
 * @param {Array<ProfilePoint>} profilePoints - Current profile points.
 * @param {Object} mouldParams - Current mould parameters.
 * @param {'standard'|'high'} resolution - STL tessellation resolution.
 * @param {Object} [options] - Additional options.
 * @param {string} [options.projectName] - Name for the ZIP folder (default: 'pottery-mould').
 * @param {boolean} [options.includeStep] - Whether to include STEP files (Pro feature).
 * @param {function(string): void} [options.onProgress] - Progress callback.
 * @returns {Promise<void>}
 */
export async function downloadMouldZip(profilePoints, mouldParams, resolution, options = {}) {
  if (typeof JSZip === 'undefined') {
    throw new Error('JSZip not loaded. Check that the CDN script tag is in index.html.');
  }

  const { projectName = 'pottery-mould', onProgress, includeStep = false } = options;

  onProgress?.('Generating files...');
  const exportData = await geometryBridge.exportParts(profilePoints, mouldParams, resolution);

  const zip = new JSZip();
  const folder = zip.folder(projectName);

  // Add STL files
  for (const [name, buffer] of Object.entries(exportData.stlBuffers)) {
    folder.file(`${name}.stl`, buffer);
  }

  // Add STEP files if requested and available
  if (includeStep && exportData.stepBuffers) {
    for (const [name, buffer] of Object.entries(exportData.stepBuffers)) {
      if (buffer && buffer.byteLength > 0) {
        folder.file(`${name}.step`, buffer);
      }
    }
  }

  // Generate comprehensive readme with plaster calculations
  const readme = generateReadme({
    partNames: exportData.partNames,
    mouldParams,
    volumes: exportData.volumes,
    resolution,
    includeStep,
  });
  folder.file('README.txt', readme);

  onProgress?.('Creating ZIP...');
  const blob = await zip.generateAsync({ type: 'blob' });

  triggerDownload(blob, `${projectName}.zip`);
  onProgress?.('Done');
}
