---
phase: 06-outer-mould-ring-assembly
plan: 01
type: execute
wave: 1
depends_on: []
files_modified:
  - js/workers/geometryWorker.js
  - js/geometryBridge.js
  - js/app.js
  - js/preview3d.js
  - index.html
autonomous: true

must_haves:
  truths:
    - "Outer mould appears in the 3D preview as a cylindrical shell surrounding the inner mould with a visible plaster cavity gap"
    - "User can select between halves (2 pieces) and quarters (4 pieces) via a split selector dropdown"
    - "Split pieces separate visually in exploded view, each as an independent scene object"
    - "Changing cavity gap or split count regenerates the outer mould in the preview"
    - "Outer mould checkbox is enabled and toggles all outer mould pieces"
  artifacts:
    - path: "js/workers/geometryWorker.js"
      provides: "generateOuterMould() and splitSolid() functions, makeBox import, outer mould parts in generateMouldParts pipeline"
      contains: "generateOuterMould"
    - path: "js/preview3d.js"
      provides: "EXPLODED_OFFSETS entries for outer-front, outer-back (and quarter variants), material assignment for outer-mould-* parts"
      contains: "outer-front"
    - path: "js/app.js"
      provides: "Outer mould settings UI wiring (cavity gap, split count), outer mould visibility toggle, outer mould parts rendered from worker result"
      contains: "cavityGap"
    - path: "index.html"
      provides: "Cavity gap slider, split count selector, enabled outer mould checkbox"
      contains: "slider-cavity-gap"
  key_links:
    - from: "js/workers/geometryWorker.js"
      to: "js/app.js"
      via: "generateMouldParts returns outer-front, outer-back (or quarter keys) in results object"
      pattern: "outer-front|outer-back"
    - from: "js/app.js"
      to: "js/preview3d.js"
      via: "updatePartMesh called for each outer mould piece"
      pattern: "updatePartMesh.*outer"
    - from: "index.html"
      to: "js/app.js"
      via: "cavity gap slider and split selector trigger regenerateMould()"
      pattern: "slider-cavity-gap|select-split-count"
---

<objective>
Generate the outer mould as a cylindrical containment wall with configurable plaster cavity gap, split it into halves or quarters using box-cutting boolean operations, and wire it into the preview with UI controls.

Purpose: The outer mould is the containment shell that holds plaster around the inner mould. Without it, there is no complete mould assembly. This plan delivers the largest piece of Phase 6 geometry -- the split outer wall -- and establishes the splitting pattern reused by the ring in Plan 06-02.

Output: Outer mould pieces visible in 3D preview, cavity gap slider, split count selector, outer mould visibility toggle enabled.
</objective>

<execution_context>
@/Users/victorhome_1/.claude/get-shit-done/workflows/execute-plan.md
@/Users/victorhome_1/.claude/get-shit-done/templates/summary.md
</execution_context>

<context>
@.planning/PROJECT.md
@.planning/ROADMAP.md
@.planning/phases/phase-6/RESEARCH.md
@.planning/phases/phase-5/05-02-SUMMARY.md
@js/workers/geometryWorker.js
@js/workers/memoryTracker.js
@js/geometryBridge.js
@js/preview3d.js
@js/app.js
@index.html
</context>

<tasks>

<task type="auto">
  <name>Task 1: Add outer mould generation and splitting to geometryWorker.js</name>
  <files>js/workers/geometryWorker.js</files>
  <action>
**A. Add makeBox to the replicad imports:**

In the module-level variables section (near `let draw = null; let setOC = null; let FaceFinder = null;`), add:

```javascript
let makeBox = null;
let makeCylinder = null;
```

In the `initialize()` function, after `FaceFinder = replicadModule.FaceFinder;`, add:

```javascript
makeBox = replicadModule.makeBox;
makeCylinder = replicadModule.makeCylinder;
```

**B. Add splitSolid() helper function (after the existing helper functions, before generateMouldParts):**

```javascript
/**
 * Split a revolved solid into halves or quarters using box-cutting.
 *
 * The solid is centered on the Z axis (revolved around Z).
 * Halves: split at Y=0 plane -> front (Y>0) and back (Y<0).
 * Quarters: split at both Y=0 and X=0 -> four quadrants.
 *
 * @param {Object} shape - The revolved replicad Solid.
 * @param {number} splitCount - 2 for halves, 4 for quarters.
 * @param {Function} track - The withCleanup track function.
 * @returns {Array<{ key: string, solid: Object }>} Named pieces.
 */
function splitSolid(shape, splitCount, track) {
  const B = 500; // Oversized cutting box dimension (much larger than any mould)

  if (splitCount === 4) {
    // Step 1: split into front/back halves at Y=0
    const cutFrontTool = track(makeBox([-B, -B, -B], [B, 0, B]));
    const frontHalf = track(shape.cut(cutFrontTool));
    const cutBackTool = track(makeBox([-B, 0, -B], [B, B, B]));
    const backHalf = track(shape.cut(cutBackTool));

    // Step 2: split each half into left/right at X=0
    const cutLeftTool = track(makeBox([-B, -B, -B], [0, B, B]));
    const cutRightTool = track(makeBox([0, -B, -B], [B, B, B]));

    const q1 = track(frontHalf.cut(cutLeftTool));  // X>0, Y>0
    const q2 = track(frontHalf.cut(cutRightTool)); // X<0, Y>0
    const q3 = track(backHalf.cut(cutLeftTool));   // X>0, Y<0
    const q4 = track(backHalf.cut(cutRightTool));  // X<0, Y<0

    return [
      { key: 'q1', solid: q1 },
      { key: 'q2', solid: q2 },
      { key: 'q3', solid: q3 },
      { key: 'q4', solid: q4 },
    ];
  }

  // Default: halves at Y=0
  const cutFrontTool = track(makeBox([-B, -B, -B], [B, 0, B]));
  const frontHalf = track(shape.cut(cutFrontTool));
  const cutBackTool = track(makeBox([-B, 0, -B], [B, B, B]));
  const backHalf = track(shape.cut(cutBackTool));

  return [
    { key: 'front', solid: frontHalf },
    { key: 'back', solid: backHalf },
  ];
}
```

**C. Add generateOuterMould() function (after splitSolid):**

```javascript
/**
 * Generate the outer mould: a cylindrical shell offset from the inner mould,
 * split into halves or quarters.
 *
 * The outer mould is a simple cylinder-like shape (uniform radius based on
 * the widest point of the pot profile + cavity gap + wall thickness).
 * This matches the ShapeCast approach: flat outer wall for easy clamping.
 *
 * IMPORTANT radius calculation:
 *   innerMouldOuterRadius = maxProfileRadius + wallThickness  (shell grows outward)
 *   outerMouldInnerRadius = innerMouldOuterRadius + cavityGap
 *   outerMouldOuterRadius = outerMouldInnerRadius + outerWallThickness
 *
 * @param {Array} scaledPoints - Shrinkage-scaled profile points (same as inner mould input).
 * @param {Array} mouldProfile - The full mould profile (with slip well if present).
 * @param {Object} mouldParams - Mould generation parameters.
 * @param {Function} track - The withCleanup track function.
 * @returns {Array<{ key: string, solid: Object }>} Named split pieces.
 */
function generateOuterMould(scaledPoints, mouldProfile, mouldParams, track) {
  const {
    wallThickness = 2.4,
    cavityGap = 25,
    splitCount = 2,
    outerWallThickness = 2.4,
  } = mouldParams;

  // Calculate outer mould dimensions
  // maxProfileRadius is the widest point of the shrinkage-scaled profile
  const maxProfileRadius = Math.max(...scaledPoints.map(p => p.x));

  // Inner mould shell grows OUTWARD by wallThickness, so its outer surface is:
  const innerMouldOuterRadius = maxProfileRadius + wallThickness;

  // Outer mould starts beyond the cavity gap
  const outerMouldInnerRadius = innerMouldOuterRadius + cavityGap;
  const outerMouldOuterRadius = outerMouldInnerRadius + outerWallThickness;

  // Height matches the full mould profile (including slip well)
  const bottomZ = mouldProfile[0].y;
  const topZ = mouldProfile[mouldProfile.length - 1].y;

  // Build outer mould as a revolved rectangular cross-section.
  // This creates a cylindrical shell (uniform radius, open top, closed bottom).
  // The profile is: inner-bottom -> inner-top -> outer-top -> outer-bottom
  // When closed back to axis by buildAndRevolve, the bottom becomes solid.
  // We only want the wall, so we build just the rectangular wall cross-section
  // and revolve it. buildAndRevolve closes to axis, which adds the bottom.
  //
  // Actually, we want the outer mould to be a hollow cylinder (open top, solid bottom).
  // The simplest approach: build a full rectangular cross-section and revolve.
  // The closing path to axis creates the bottom plate, which is what we want.
  const outerProfile = [
    { x: outerMouldInnerRadius, y: bottomZ, type: 'line' },
    { x: outerMouldInnerRadius, y: topZ, type: 'line' },
    { x: outerMouldOuterRadius, y: topZ, type: 'line' },
    { x: outerMouldOuterRadius, y: bottomZ, type: 'line' },
  ];

  const outerSolid = track(buildAndRevolve(outerProfile));

  // Split into halves or quarters
  return splitSolid(outerSolid, splitCount, track);
}
```

**D. Integrate outer mould into generateMouldParts():**

In the existing `generateMouldParts()` function, AFTER the inner-mould section (after `results['inner-mould'] = toTransferableMesh(shelledMould.mesh(meshOpts));`), add the outer mould generation:

```javascript
    // Outer mould: cylindrical shell split into halves or quarters
    try {
      const outerPieces = generateOuterMould(scaledPoints, mouldProfile, mouldParams, track);
      for (const piece of outerPieces) {
        results[`outer-${piece.key}`] = toTransferableMesh(piece.solid.mesh(meshOpts));
      }
    } catch (outerErr) {
      console.warn('[worker] Outer mould generation failed:', outerErr.message);
      results['outer-mould-error'] = {
        message: `Outer mould failed: ${outerErr.message}`,
      };
    }
```

Also update the mouldParams destructuring at the top of `generateMouldParts()` to include the new parameters with defaults:

```javascript
  const {
    shrinkageRate = 0.13,
    wallThickness = 2.4,
    slipWellType = 'regular',
    cavityGap = 25,
    splitCount = 2,
    outerWallThickness = 2.4,
  } = mouldParams || {};
```

IMPORTANT: The `mouldProfile` variable (profile with slip well extension) is already computed before the inner mould revolve. Pass it to `generateOuterMould()` so the outer mould height matches the inner mould height including any slip well.

Also ensure the `mouldParams` object is passed through to `generateOuterMould()` -- it already contains all the needed fields from the destructured defaults.

**E. Fix the transferList builder to handle error entries:**

The existing transferList builder in the 'generateMould' case already checks `if (part.vertices)` before adding buffers, which correctly skips error entries like `outer-mould-error`. No change needed.
  </action>
  <verify>
1. Check makeBox import: `grep "makeBox = replicadModule.makeBox" js/workers/geometryWorker.js`
2. Check makeCylinder import: `grep "makeCylinder = replicadModule.makeCylinder" js/workers/geometryWorker.js`
3. Check splitSolid function: `grep "function splitSolid" js/workers/geometryWorker.js`
4. Check generateOuterMould function: `grep "function generateOuterMould" js/workers/geometryWorker.js`
5. Check outer mould integrated into pipeline: `grep "outer-.*piece.key" js/workers/geometryWorker.js`
6. Check cavityGap in mouldParams destructuring: `grep "cavityGap" js/workers/geometryWorker.js`
7. Check error handling: `grep "outer-mould-error" js/workers/geometryWorker.js`
  </verify>
  <done>
Worker generates outer mould as a cylindrical shell offset from inner mould by cavityGap, split into halves (outer-front, outer-back) or quarters (outer-q1 through outer-q4). Error handling returns outer-mould-error alongside other successful parts. splitSolid() is a reusable helper for Plan 06-02's ring splitting.
  </done>
</task>

<task type="auto">
  <name>Task 2: Wire outer mould into preview, add UI controls, enable visibility toggle</name>
  <files>js/preview3d.js, js/app.js, index.html</files>
  <action>
**A. Update EXPLODED_OFFSETS in preview3d.js:**

Replace the existing EXPLODED_OFFSETS with expanded entries that handle individual split pieces. The outer mould pieces should appear at the same vertical offset (they are split laterally, not vertically):

```javascript
const EXPLODED_OFFSETS = {
  'pot':          0,
  'inner-mould':  100,
  'outer-front':  200,
  'outer-back':   200,
  'outer-q1':     200,
  'outer-q2':     200,
  'outer-q3':     200,
  'outer-q4':     200,
  'ring-front':   -50,
  'ring-back':    -50,
  'ring-q1':      -50,
  'ring-q2':      -50,
  'ring-q3':      -50,
  'ring-q4':      -50,
  'proof':        300,
};
```

Remove the old 'outer-mould' and 'ring' entries since parts are now individually named.

**B. Update createMaterialForPart() in preview3d.js to match outer-* and ring-* parts:**

Replace the exact string match with a prefix check:

```javascript
function createMaterialForPart(partName) {
  if (partName.startsWith('inner-mould') || partName.startsWith('outer-') || partName.startsWith('ring-')) {
    return new THREE.MeshStandardMaterial(MOULD_MATERIAL_PARAMS);
  }
  if (partName === 'proof') {
    return new THREE.MeshStandardMaterial(PROOF_MATERIAL_PARAMS);
  }
  return createTerraCottaMaterial();
}
```

**C. Update setPartVisibility() in preview3d.js -- add a group visibility helper:**

Add a new export function that sets visibility for all parts matching a prefix:

```javascript
/**
 * Set visibility for all parts matching a name prefix.
 *
 * @param {string} prefix - Part name prefix (e.g., 'outer-' matches 'outer-front', 'outer-back').
 * @param {boolean} visible - Whether matching parts should be visible.
 */
export function setPartGroupVisibility(prefix, visible) {
  for (const [name, entry] of parts) {
    if (name.startsWith(prefix)) {
      entry.group.visible = visible;
    }
  }
}
```

**D. Add outer mould settings to index.html:**

In the `#mould-settings` div (after the slip well selector), add:

```html
<div class="slider-field">
  <label for="slider-cavity-gap">Plaster cavity</label>
  <input type="range" id="slider-cavity-gap" min="10" max="50" step="1" value="25" />
  <span class="slider-value" id="val-cavity-gap">25</span>
  <span class="slider-unit">mm</span>
</div>
<div class="preset-field">
  <label for="select-split-count">Mould split</label>
  <select id="select-split-count">
    <option value="2" selected>Halves (2 pieces)</option>
    <option value="4">Quarters (4 pieces)</option>
  </select>
</div>
```

**E. Enable the Outer Mould checkbox in index.html:**

Change the outer mould checkbox from disabled to enabled:

```html
<!-- Before: -->
<input type="checkbox" id="chk-show-outer" checked disabled> Outer Mould

<!-- After: -->
<input type="checkbox" id="chk-show-outer" checked> Outer Mould
```

Keep the Ring checkbox disabled (enabled in Plan 06-02).

**F. Add cavityGap and splitCount to mouldParams in app.js:**

Update the `mouldParams` object:

```javascript
const mouldParams = {
  shrinkageRate: 0.13,
  wallThickness: 2.4,
  slipWellType: 'regular',
  cavityGap: 25,
  splitCount: 2,
  outerWallThickness: 2.4,
};
```

**G. Wire outer mould settings in app.js initMouldSettings():**

Add at the end of `initMouldSettings()`:

```javascript
  // Wire cavity gap slider
  const sliderCavityGap = document.getElementById('slider-cavity-gap');
  const valCavityGap = document.getElementById('val-cavity-gap');
  if (sliderCavityGap) {
    mouldParams.cavityGap = parseFloat(sliderCavityGap.value);
    sliderCavityGap.addEventListener('input', () => {
      const mm = parseFloat(sliderCavityGap.value);
      if (valCavityGap) valCavityGap.textContent = mm;
      mouldParams.cavityGap = mm;
      regenerateMould();
    });
  }

  // Wire split count selector
  const selectSplitCount = document.getElementById('select-split-count');
  if (selectSplitCount) {
    mouldParams.splitCount = parseInt(selectSplitCount.value, 10);
    selectSplitCount.addEventListener('change', () => {
      mouldParams.splitCount = parseInt(selectSplitCount.value, 10);
      regenerateMould();
    });
  }
```

**H. Update onProfileChange() and regenerateMould() in app.js to handle outer mould parts:**

In `onProfileChange()`, after the existing inner-mould handling, add outer mould piece handling. The worker returns keys like `outer-front`, `outer-back`, `outer-q1`, etc. Iterate through the result and update any part whose key starts with `outer-`:

```javascript
    // Update outer mould pieces (outer-front, outer-back, or outer-q1..q4)
    for (const [partName, meshData] of Object.entries(mouldResult)) {
      if (partName.startsWith('outer-') && !partName.endsWith('-error') && meshData.vertices) {
        preview3d.updatePartMesh(partName, meshData);
      }
    }
```

IMPORTANT: When the split count changes (e.g., from halves to quarters), the old pieces must be removed. Before adding new outer pieces, clear all existing outer-* parts:

Add a helper to clear parts by prefix. In the section where outer mould pieces are processed, first remove old ones:

```javascript
    // Clear previous outer mould pieces (split count may have changed)
    preview3d.removePartsByPrefix('outer-');
```

This requires adding `removePartsByPrefix()` to preview3d.js:

```javascript
/**
 * Remove and dispose all parts matching a name prefix.
 * Used when split count changes (halves -> quarters or vice versa).
 *
 * @param {string} prefix - Part name prefix to match.
 */
export function removePartsByPrefix(prefix) {
  for (const [name, entry] of parts) {
    if (name.startsWith(prefix)) {
      disposePart(entry);
      parts.delete(name);
    }
  }
}
```

Apply the same pattern in `regenerateMould()`.

**I. Wire outer mould visibility toggle in app.js initViewControls():**

After the existing proof checkbox wiring, add:

```javascript
  const chkOuter = document.getElementById('chk-show-outer');
  if (chkOuter) {
    chkOuter.addEventListener('change', () => {
      preview3d.setPartGroupVisibility('outer-', chkOuter.checked);
    });
  }
```

**J. Handle outer-mould-error in app.js:**

In both `onProfileChange()` and `regenerateMould()`, after the outer mould piece loop, add:

```javascript
    if (mouldResult['outer-mould-error']) {
      console.warn('[app] Outer mould error:', mouldResult['outer-mould-error'].message);
    }
```
  </action>
  <verify>
1. Check EXPLODED_OFFSETS updated: `grep "outer-front\|outer-back\|outer-q1" js/preview3d.js`
2. Check material for outer parts: `grep "startsWith.*outer" js/preview3d.js`
3. Check setPartGroupVisibility export: `grep "setPartGroupVisibility" js/preview3d.js`
4. Check removePartsByPrefix export: `grep "removePartsByPrefix" js/preview3d.js`
5. Check cavity gap slider in HTML: `grep "slider-cavity-gap" index.html`
6. Check split count selector in HTML: `grep "select-split-count" index.html`
7. Check outer mould checkbox enabled: `grep "chk-show-outer" index.html` should NOT show "disabled"
8. Check mouldParams has cavityGap: `grep "cavityGap" js/app.js`
9. Check outer mould visibility wiring: `grep "chk-show-outer\|setPartGroupVisibility" js/app.js`
10. Open app in browser: outer mould shell appears around inner mould with visible gap. Switching to quarters shows 4 pieces. Exploded view separates them. Checkbox toggles all outer pieces.
  </verify>
  <done>
Outer mould shell renders in 3D preview with configurable plaster cavity gap (10-50mm slider, default 25mm) and split count (halves/quarters dropdown). Outer Mould visibility checkbox enabled. Exploded view separates all pieces. Changing cavity gap or split count triggers regeneration. Old pieces are cleaned up when split count changes.
  </done>
</task>

</tasks>

<verification>
1. Outer mould cylindrical shell wraps around inner mould with visible plaster cavity gap
2. Default cavity gap is 25mm (configurable via slider)
3. Halves mode produces 2 pieces (outer-front, outer-back), quarters mode produces 4 (outer-q1 through outer-q4)
4. Split uses makeBox + cut boolean operations (not manual geometry construction)
5. Outer mould height matches inner mould height (including slip well)
6. Outer mould inner radius = maxProfileRadius + wallThickness + cavityGap (accounts for shell growing outward)
7. All WASM objects tracked via withCleanup for memory management
8. Error in outer mould generation does not prevent proof + inner mould from displaying
9. Changing split count cleans up old pieces before adding new ones
10. Exploded view vertically separates outer mould from inner mould and proof
</verification>

<success_criteria>
- Outer mould appears as a blue-grey cylindrical shell offset from the inner mould by 25mm (default)
- Halves: 2 pieces visible in exploded view, quarters: 4 pieces visible
- Cavity gap slider (10-50mm) regenerates outer mould on change
- Split count dropdown (halves/quarters) regenerates with correct piece count
- Outer Mould checkbox toggles all outer pieces on/off
- Profile edits regenerate outer mould along with proof + inner mould
</success_criteria>

<output>
After completion, create `.planning/phases/phase-6/06-01-SUMMARY.md`
</output>
